spring:
  application:
    name: personal-finance-tracker
  profiles:
    active: test

  datasource:
    url: jdbc:postgresql://localhost:5432/PersonalFinanceDB
    username: postgres
    password: VSKOROB2
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/PersonalFinanceDB
    user: postgres
    password: VSKOROB2
    driver-class-name: org.postgresql.Driver
    change-log: db/changelog/changelog.yaml
    contexts: dev
    default-schema: public
    drop-first: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
