spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/PersonalFinanceDB
    username: postgres
    password: VSKOROB2

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    url: jdbc:postgresql://postgres_db:5432/PersonalFinanceDB
    user: postgres
    password: VSKOROB2
    change-log: db/changelog/changelog.yaml
    drop-first: false